[package]
name = "rustbee-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
poll-promise = { version = "0.3.0", features = ["tokio"] }
rustbee-common = { path = "../rustbee-common" }
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread"] }
