[doc]
_default:
    @just -l --list-heading $'Available commands:\n' --unsorted

[no-exit-message]
@build:
    cargo build --release
    echo -e "$purple[Rustbee Daemon] Finished compiling !$white"

@install:
    sudo ln -sf ./target/release/rustbee-daemon /bin/rustbee-daemon
    echo -e "${purple}Rustbee Daemon symlinked to /bin dir$white"

# TODO: add exec to path
@uninstall:
    -cargo clean > /dev/null 2>&1
    -sudo rm /bin/rustbee-daemon > /dev/null 2>&1
