[private]
_default:
    @echo "[ERROR] Just commands must be run on the root of the project"

[private]
@build:
    cargo build --release
    echo -e "$purple[Rustbee Daemon] Finished compiling !$white"

[private]
@install:
    sudo ln -sf $PWD/target/release/rustbee-daemon /bin/rustbee-daemon
    echo -e "${purple}Rustbee Daemon symlinked to /bin dir$white"

# TODO: add exec to path
[private]
@uninstall:
    -cargo clean > /dev/null 2>&1
    -sudo rm /bin/rustbee-daemon > /dev/null 2>&1
