[package]
name = "rustbee-common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[features]
default = []
ffi = []

[dependencies]
btleplug = "0.11.5"
color_space = "0.5.4"
futures = "0.3.30"
interprocess = { version = "2.2.0", features = ["tokio"] }
tokio = { version = "1.39.2", features = ["fs", "process"] }
uuid = "1.10.0"
